INSERT INTO QUESTIONS (TITLE, AUTHOR, PRICE) VALUES ('The Iliad', 'Homer', 300);
INSERT INTO QUESTIONS (TITLE, AUTHOR, PRICE) VALUES ('The Hitchhikers Guide to the Galaxy', 'Douglas Adams', 500);
INSERT INTO QUESTIONS (TITLE, AUTHOR, PRICE) VALUES ('Pippi Longstocking', 'Astrid Lindgren', 250);

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PASSWORD) VALUES('Donald', 'Duck', 'donald@disney.com', '123');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PASSWORD) VALUES('Daisy', 'Duck', 'daisy@disney.com', 'abc');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, PASSWORD) VALUES('Scrooge', 'McDuck', 'scrooge@disney.com', '321');

INSERT INTO PURCHASE (BOOK_ID, CUSTOMER_ID, PURCHASE_DATE) VALUES ((SELECT ID FROM QUESTIONS WHERE AUTHOR = 'Douglas Adams'), (SELECT ID FROM CUSTOMER WHERE FIRST_NAME = 'Donald'), '2019-01-07');

