CREATE TABLE QUESTIONS(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(64) NOT NULL,
  AUTHOR VARCHAR(64) NOT NULL,
  PRICE BIGINT NOT NULL
);

CREATE TABLE CUSTOMER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  PASSWORD VARCHAR(64)
);

CREATE TABLE PURCHASE(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BOOK_ID BIGINT NOT NULL,
  CUSTOMER_ID BIGINT NOT NULL,
  PURCHASE_DATE DATE
);

ALTER TABLE PURCHASE ADD FOREIGN KEY (BOOK_ID) REFERENCES QUESTIONS(ID);
ALTER TABLE PURCHASE ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID);
CREATE INDEX IDX_RES_DATE_ ON PURCHASE(PURCHASE_DATE);
